name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown converter
        run: npm install -g marked

      # Convert README (which should NOT contain the H1 title) to pure HTML
      - name: Convert README.md to content.html (no header ids)
        run: marked README.md --no-header-ids -o content.html

      # Inject the converted HTML into our template
      - name: Build index.html from template
        run: |
          sed -e '/<!--CONTENT-->/{
            r content.html
            d
          }' template.html > index.html

      # Deploy static site (this action drops a .nojekyll by default)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          force_orphan: true
