name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main  # deploy when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: pandoc README.md -o index.html --standalone --metadata title="Bundi/Kitab Docs"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
